// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2ShAxVskANTOxiGQ2C8fSfBeHaiz08I',
    appId: '1:220894978112:web:f07d04a3abff917dd3bfa5',
    messagingSenderId: '220894978112',
    projectId: 'todoappvb',
    authDomain: 'todoappvb.firebaseapp.com',
    storageBucket: 'todoappvb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwLVeG_Gbc3_B3gw7xCUmFK6ALPBtDNvQ',
    appId: '1:220894978112:android:1510e984f8ac23fcd3bfa5',
    messagingSenderId: '220894978112',
    projectId: 'todoappvb',
    storageBucket: 'todoappvb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_9jXFL6K6bxpuFosyYhJoD7ZXPFEzsA',
    appId: '1:220894978112:ios:6325c8ebb9ef1850d3bfa5',
    messagingSenderId: '220894978112',
    projectId: 'todoappvb',
    storageBucket: 'todoappvb.appspot.com',
    iosBundleId: 'com.example.todoappvb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_9jXFL6K6bxpuFosyYhJoD7ZXPFEzsA',
    appId: '1:220894978112:ios:6325c8ebb9ef1850d3bfa5',
    messagingSenderId: '220894978112',
    projectId: 'todoappvb',
    storageBucket: 'todoappvb.appspot.com',
    iosBundleId: 'com.example.todoappvb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2ShAxVskANTOxiGQ2C8fSfBeHaiz08I',
    appId: '1:220894978112:web:a7f6de9f104e5d6ad3bfa5',
    messagingSenderId: '220894978112',
    projectId: 'todoappvb',
    authDomain: 'todoappvb.firebaseapp.com',
    storageBucket: 'todoappvb.appspot.com',
  );
}
